#!/usr/bin/env bash
# ============================================================
# OPTISEC Recon Pro v4.0 SINGULARITY — One-Command Deployer
# Usage: ./deploy.sh [--no-ssl] [--update] [--logs] [--down]
# ============================================================
set -euo pipefail

# ── Colors ────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
CYAN='\033[0;36m'; BOLD='\033[1m'; NC='\033[0m'

log()  { echo -e "${GREEN}[✔]${NC} $*"; }
warn() { echo -e "${YELLOW}[!]${NC} $*"; }
err()  { echo -e "${RED}[✘]${NC} $*" >&2; exit 1; }
info() { echo -e "${CYAN}[→]${NC} $*"; }

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

# ── Parse flags ──────────────────────────────────────────
NO_SSL=false; UPDATE=false; SHOW_LOGS=false; TEARDOWN=false
for arg in "$@"; do
  case $arg in
    --no-ssl)   NO_SSL=true      ;;
    --update)   UPDATE=true      ;;
    --logs)     SHOW_LOGS=true   ;;
    --down)     TEARDOWN=true    ;;
    --help|-h)
      echo "Usage: $0 [--no-ssl] [--update] [--logs] [--down]"
      echo "  --no-ssl   Skip SSL setup (HTTP only, port 80)"
      echo "  --update   Pull latest code and rebuild images"
      echo "  --logs     Tail logs after deployment"
      echo "  --down     Stop and remove all containers + volumes"
      exit 0 ;;
  esac
done

# ── Banner ────────────────────────────────────────────────
echo -e "${BOLD}${CYAN}"
echo "  ╔═══════════════════════════════════════════════╗"
echo "  ║   OPTISEC Recon Pro v4.0 SINGULARITY Deploy  ║"
echo "  ╚═══════════════════════════════════════════════╝"
echo -e "${NC}"

# ── Teardown mode ─────────────────────────────────────────
if $TEARDOWN; then
  warn "Stopping all OPTISEC containers and removing volumes..."
  docker compose down -v --remove-orphans
  log "Teardown complete."
  exit 0
fi

# ── Prerequisites ─────────────────────────────────────────
info "Checking prerequisites..."
command -v docker  >/dev/null || err "Docker is not installed. Install from https://docs.docker.com/get-docker/"
command -v docker compose version >/dev/null 2>&1 || \
  docker-compose version >/dev/null 2>&1 || \
  err "Docker Compose is not installed."
log "Docker $(docker --version | awk '{print $3}' | tr -d ',')"

# ── .env setup ───────────────────────────────────────────
if [ ! -f ".env" ]; then
  info "Creating .env from .env.example..."
  if [ -f ".env.example" ]; then
    cp .env.example .env
  else
    # Generate minimal .env
    JWT_SECRET=$(python3 -c "import secrets; print(secrets.token_hex(32))" 2>/dev/null || \
                 openssl rand -hex 32)
    PG_PASS=$(python3 -c "import secrets; print(secrets.token_urlsafe(20))" 2>/dev/null || \
              openssl rand -base64 16 | tr -dc 'a-zA-Z0-9' | head -c 20)
    cat > .env << EOF
# ── OPTISEC Environment Configuration ──────────────────
# Generated by deploy.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)

# Security — CHANGE THESE!
JWT_SECRET=${JWT_SECRET}
OPTISEC_LICENSE_SECRET=optisec-license-secret-change-me

# Database
POSTGRES_PASSWORD=${PG_PASS}
DATABASE_URL=postgresql+asyncpg://optisec:${PG_PASS}@db:5432/optisec

# First admin account (used only on first run)
FIRST_ADMIN_USER=admin
FIRST_ADMIN_EMAIL=admin@optisec.local
FIRST_ADMIN_PASSWORD=Optisec123!

# AI features (optional)
GROQ_API_KEY=

# Bug Bounty (optional)
HACKERONE_USERNAME=
HACKERONE_API_TOKEN=
BUGCROWD_API_TOKEN=
INTIGRITI_API_TOKEN=

# CVE Submission (optional)
NVD_API_KEY=
CVE_CNA_ORG=
CVE_CNA_USERNAME=
CVE_CNA_API_KEY=

# OTX Threat Intel (optional)
OTX_API_KEY=

# JWT expiry
JWT_EXPIRE_HOURS=24
EOF
  fi
  warn ".env created — review it before continuing!"
  echo ""
  echo -e "${YELLOW}  Edit .env now? (press Ctrl+C to abort and edit, or Enter to continue)${NC}"
  read -r || true
fi

# ── SSL certificates ──────────────────────────────────────
if $NO_SSL; then
  info "HTTP-only mode — patching nginx.conf..."
  # Swap HTTPS block for HTTP-only block in a temp copy
  # The nginx.conf already contains the commented HTTP-only block;
  # we create an override that uses only port 80.
  mkdir -p certs  # keep volume mount happy
  # Use sed to activate the commented HTTP-only server block
  if ! grep -q "HTTP-only mode active" nginx.conf; then
    sed -i 's|listen 80;$|listen 80; # HTTP-only mode active|' nginx.conf 2>/dev/null || true
  fi
  warn "SSL disabled — traffic will be unencrypted on port 80."
else
  # Check certs exist; if not, try Let's Encrypt via certbot
  if [ ! -f "certs/fullchain.pem" ]; then
    warn "SSL certs not found in ./certs/"
    echo ""
    echo "  Options:"
    echo "  1) Place your certs:  certs/fullchain.pem  certs/privkey.pem"
    echo "  2) Generate self-signed (dev/test only):"
    echo "     mkdir -p certs && openssl req -x509 -nodes -days 365 \\"
    echo "       -newkey rsa:2048 -keyout certs/privkey.pem \\"
    echo "       -out certs/fullchain.pem -subj '/CN=optisec.local'"
    echo "  3) Re-run with --no-ssl to skip SSL"
    echo ""
    echo -e "${YELLOW}Generate self-signed cert now? [y/N]${NC} "
    read -r gen_cert
    if [[ "${gen_cert,,}" == "y" ]]; then
      mkdir -p certs
      openssl req -x509 -nodes -days 365 \
        -newkey rsa:2048 \
        -keyout certs/privkey.pem \
        -out certs/fullchain.pem \
        -subj "/CN=optisec.local" 2>/dev/null
      log "Self-signed certificate generated."
    else
      err "Provide SSL certs in ./certs/ or use --no-ssl"
    fi
  else
    log "SSL certificates found."
  fi
fi

# ── Static files volume ───────────────────────────────────
# Ensure nginx can serve static files; copy to named volume later via app container
log "Static directory verified."

# ── Pull / update ─────────────────────────────────────────
if $UPDATE; then
  info "Pulling latest code..."
  git pull --ff-only 2>/dev/null || warn "git pull failed — deploying with current code"
fi

# ── Build & start ─────────────────────────────────────────
info "Building Docker images..."
docker compose build --pull

info "Starting services..."
docker compose up -d --remove-orphans

# ── Wait for app health ───────────────────────────────────
info "Waiting for OPTISEC app to be healthy..."
WAIT=0
until docker compose exec -T app curl -fs http://localhost:8000/ >/dev/null 2>&1; do
  if [ $WAIT -ge 60 ]; then
    err "App did not become healthy in 60 s. Check logs: docker compose logs app"
  fi
  printf "."
  sleep 3
  WAIT=$((WAIT + 3))
done
echo ""
log "Application is healthy!"

# ── Copy static files into nginx-accessible volume ────────
docker compose exec -T app \
  cp -r /app/web/static/. /app/static/ 2>/dev/null || \
  warn "Could not copy static files (non-fatal, they're served by app anyway)"

# ── Summary ───────────────────────────────────────────────
SERVER_IP=$(curl -s --connect-timeout 3 ifconfig.me 2>/dev/null || \
            hostname -I 2>/dev/null | awk '{print $1}' || echo "YOUR_SERVER_IP")

echo ""
echo -e "${BOLD}${GREEN}╔══════════════════════════════════════════════════╗${NC}"
echo -e "${BOLD}${GREEN}║   OPTISEC deployed successfully!                 ║${NC}"
echo -e "${BOLD}${GREEN}╚══════════════════════════════════════════════════╝${NC}"
echo ""
if $NO_SSL; then
  echo -e "  ${CYAN}Landing:${NC}   http://${SERVER_IP}/"
  echo -e "  ${CYAN}Login:${NC}     http://${SERVER_IP}/login"
  echo -e "  ${CYAN}Swagger:${NC}   http://${SERVER_IP}/docs"
  echo -e "  ${CYAN}Demo:${NC}      http://${SERVER_IP}/demo"
else
  echo -e "  ${CYAN}Landing:${NC}   https://${SERVER_IP}/"
  echo -e "  ${CYAN}Login:${NC}     https://${SERVER_IP}/login"
  echo -e "  ${CYAN}Swagger:${NC}   https://${SERVER_IP}/docs"
  echo -e "  ${CYAN}Demo:${NC}      https://${SERVER_IP}/demo"
fi
echo ""
echo -e "  ${YELLOW}Admin:${NC}     admin / Optisec123!  (change after first login!)"
echo -e "  ${YELLOW}Demo:${NC}      demo / Demo@optisec1"
echo ""
echo -e "  Useful commands:"
echo -e "  ${CYAN}docker compose logs -f app${NC}    — app logs"
echo -e "  ${CYAN}docker compose ps${NC}              — container status"
echo -e "  ${CYAN}./deploy.sh --update${NC}           — update to latest"
echo -e "  ${CYAN}./deploy.sh --down${NC}             — tear everything down"
echo ""

# ── Tail logs (optional) ──────────────────────────────────
if $SHOW_LOGS; then
  info "Tailing logs (Ctrl+C to stop)..."
  docker compose logs -f
fi
