"""eternal_core_tables

Revision ID: ffb72a0f36f5
Revises: 
Create Date: 2026-08-16 20:14:32.259775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import app.models.eternal.base

# revision identifiers, used by Alembic.
revision: str = 'ffb72a0f36f5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('action', sa.String(length=256), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('targets',
    sa.Column('input_type', sa.Enum('EMAIL', 'PHONE', 'IP', 'IMAGE', 'PLATE', name='target_input_type'), nullable=False),
    sa.Column('input_value', app.models.eternal.base.EncryptedString(length=512), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_targets_session_id'), 'targets', ['session_id'], unique=False)
    op.create_table('recon_artifacts',
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.String(length=128), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['target_id'], ['targets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recon_artifacts_target_id'), 'recon_artifacts', ['target_id'], unique=False)
    op.create_index(op.f('ix_recon_artifacts_valid_to'), 'recon_artifacts', ['valid_to'], unique=False)
    op.create_table('simulation_steps',
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('mitre_tactic', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['target_id'], ['targets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_simulation_steps_target_id'), 'simulation_steps', ['target_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_simulation_steps_target_id'), table_name='simulation_steps')
    op.drop_table('simulation_steps')
    op.drop_index(op.f('ix_recon_artifacts_valid_to'), table_name='recon_artifacts')
    op.drop_index(op.f('ix_recon_artifacts_target_id'), table_name='recon_artifacts')
    op.drop_table('recon_artifacts')
    op.drop_index(op.f('ix_targets_session_id'), table_name='targets')
    op.drop_table('targets')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
